// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxgoznnnuwnmvwlriwjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4Z296bm5udXdubXZ3bHJpd2p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNzEzMTAsImV4cCI6MjA2NjY0NzMxMH0.Hrf30eNcGEdsLMVRPKplZp5Vp0MmA2Pt7_J6dWHZdK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);