// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuzxignvxszejxdteknv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1enhpZ252eHN6ZWp4ZHRla252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDgyNjcsImV4cCI6MjA2NzA4NDI2N30.BAXx1yt3qF3Kf6NLpuAd0q_iF94X3I1RDjMfBqouSZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});